CREATE TABLE IF NOT EXISTS users(
id INT UNSIGNED NOT NULL  AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(63) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
salt VARCHAR(63) NOT NULL,
email VARCHAR(127)
);