Begin;
CREATE TABLE IF NOT EXISTS 'users' (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(63) UNIQUE NOT NULL,
	passwort VARCHAR(255) NOT NULL,
	salt VARCHAR(63) NOT NULL,
	email VARCHAR(127)
);
Commit;