CREATE TABLE IF NOT EXISTS sessions(
token VARCHAR(128) NOT NULL PRIMARY KEY,
end_date TIMESTAMP NOT NULL,
user_id INT UNSIGNED,
CONSTRAINT `fk_u_id` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);