CREATE TABLE IF NOT EXISTS answers (
id INT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
possible_date_id INT UNSIGNED NOT NULL,
user_id INT UNSIGNED NOT NULL.
answer VARCHAR(1) NOT NULL,
CONSTRAINT `fk_p_id` FOREIGN KEY (possible_date_id) REFERENCES events (id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT `fk_u_id` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);

