Begin;
CREATE TABLE IF NOT EXISTS 'events' (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY AUTO_INCREMENT,
	event_date TIMESTAMP NOT NULL,
	location VARCHAR(127),
	street VARCHAR(127),
	city VARCHAR(127),
	text VARCHAR(2047)
);
Commit;