Begin;
CREATE TABLE IF NOT EXISTS 'sessions' (
	token VARCHAR(127) UNIQUE PRIMARY KEY NOT NULL,
	end_date TIMESTAMP NOT NULL,
	user_id INT,
	CONSTRAINT `fk_u_id` FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
Commit;